#= require jquery/dist/jquery
#= require jquery.cookie/jquery.cookie
#= require jquery.counterup/jquery.counterup.min
#= require jquery-parallax.js/parallax.min
#= require jquery.scrollto/jquery.scrollTo.min
#= require js-cookie/src/js.cookie
#= require bootstrap/dist/js/bootstrap
#= require bootstrap-select/dist/js/bootstrap-select.min
#= require bootstrap-slider/dist/bootstrap-slider.min
#= require owl.carousel/dist/owl.carousel.min
#= require owl.carousel2.thumbs/dist/owl.carousel2.thumbs.min
#= require parsleyjs/dist/parsley.min
#= require parsleyjs/dist/i18n/it
#= require waypoints/lib/jquery.waypoints.min
#= require general
#= require_tree
#= require_self
